config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "blogs#index"
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

  protected

  def resource_not_found
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:success] = "Blog Entry has been created"
      redirect_to blogs_path
    else
      flash.now[:danger] = "Blog entry has not been created"
      render :new

    end
  end
  def edit
  end

  def show
  end

  def update
    if @blog.update(blog_params)
      flash[:success] = "Blog Entry has been updated"
      redirect_to @blog
    else
      flash.now[:danger] = "Blog Entry has not been updated"
      render :edit
    end
  end

  def destroy
    if @blog.destroy
      flash[:success] = "Blog Entry has been deleted"
      redirect_to blogs_path
    end
  end

  protected

    def resource_not_found
      message = "The blog you are looking for could not be found"
      flash[:alert] = message
      redirect_to root_path
    end

  private

    def blog_params
      params.require(:blog).permit(:title, :body)
    end

    def set_article
      @blog = Blog.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@blog, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <% if @blog.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title"> <%= pluralize(@blog.errors.count, 'error') %> prohibited the entry from being saved</h2>
            <div class="panel-body">
              <ul>
                <% @blog.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-11">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title of Blog', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :body %>
        </div>
        <div class="col-md-11">
          <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of Blog' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: "btn btn-primary btn-large pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<h2 class="text-center">Editing Blog Entry</h2>

<%= render  "form" %>

app/views/blogs/index.html.erb
<%= link_to  "New Blog Entry", new_blog_path, class: "btn btn-default btn-lg", id: "New-Blog_Entry-btn" %>

<% if @blogs.empty? %>
  <h1 id="no-blog_entries">No Blog Entries Created</h1>
<% else %>
  <% @blogs.each do |b| %>
    <div class="well well-lg">
      <div class="blog-title">
        <%= link_to b.title, blog_path(b) %>
      </div>
      <div class="blog-body">
        <%= truncate(b.body, length: 500) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<h2 class="text-center">Adding New Blog Entry</h2>

<%= render  "form" %>

app/views/blogs/show.html.erb
<article class="detail-blog">
  <h1 class="blog-detail-title"> <%= @blog.title %></h1>
  <div class="glyphicon glyphicon-calendar" id="blog-date"> <%= @blog.created_at.strftime("%b %d %Y") %></div>
  <div class="blog body"> <%= @blog.body %></div>

  <div class="edit-delete">
    <%= link_to  "Edit Blog Entry", edit_blog_path(@blog), class: "btn btn-warning btn-lg" %>
    <%= link_to  "Delete Entry", blog_path(@blog),method: :delete, data: {confirm: "Are you sure you want to delete article?"}, class: "btn btn-danger btn-lg btn-space" %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jpl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Blog App", root_path, class: "navbar-brand" %>
          </div>
          <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Blog", root_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, msg| %>
            <div class="text-center alert alert-<%= key == 'notice'?  'success': 'danger'  %>">
              <%= msg %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>